# Generated by Django 4.2.29 on 2026-03-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_courseitem_videolesson_textlesson_test_course_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="studentanswer",
            name="selected_option",
        ),
        migrations.RemoveField(
            model_name="testattempt",
            name="score",
        ),
        migrations.AddField(
            model_name="answeroption",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="answer_options/"),
        ),
        migrations.AddField(
            model_name="question",
            name="max_score",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single_choice", "Single choice"),
                    ("multiple_choice", "Multiple choice"),
                    ("text", "Text answer"),
                    ("file", "File answer"),
                ],
                default="single_choice",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="awarded_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="file_answer",
            field=models.FileField(blank=True, null=True, upload_to="student_answers/"),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="text_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("checking", "Checking"),
                    ("checked", "Checked"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="total_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="text",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="courses.testattempt",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="course_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_block",
                to="courses.courseitem",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("test", "order")},
        ),
        migrations.CreateModel(
            name="StudentSelectedOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_in_answers",
                        to="courses.answeroption",
                    ),
                ),
                (
                    "student_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_options",
                        to="courses.studentanswer",
                    ),
                ),
            ],
            options={
                "unique_together": {("student_answer", "option")},
            },
        ),
    ]
